name: beebuddy
region: nyc

databases:
  - name: beebuddy-pg
    cluster_name: beebuddy-pg
    engine: PG
    version: "16"
    production: true
    db_name: defaultdb
    db_user: doadmin
  - name: beebuddy-valkey
    cluster_name: beebuddy-valkey
    engine: VALKEY
    version: "8"
    production: true

envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${beebuddy-pg.DATABASE_URL}
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${beebuddy-valkey.DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    type: SECRET
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    type: SECRET
  - key: S3_BUCKET
    scope: RUN_TIME
    value: beebuddy-photos
  - key: S3_ENDPOINT_URL
    scope: RUN_TIME
    value: https://atl1.digitaloceanspaces.com
  - key: S3_REGION
    scope: RUN_TIME
    value: atl1
  - key: LLM_PROVIDER
    scope: RUN_TIME
    value: anthropic
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SENDGRID_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_FROM_ADDRESS
    scope: RUN_TIME
    value: no-reply@beebuddyai.com

services:
  - name: api
    github:
      repo: jsrobinson3/BeeBuddy
      branch: main
      deploy_on_push: true
    source_dir: apps/api
    dockerfile_path: apps/api/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: professional-xs
    run_command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: COOKIE_SECURE
        scope: RUN_TIME
        value: "true"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: '["https://beebuddy.app"]'

workers:
  - name: celery-worker
    github:
      repo: jsrobinson3/BeeBuddy
      branch: main
      deploy_on_push: true
    source_dir: apps/api
    dockerfile_path: apps/api/Dockerfile
    instance_count: 1
    instance_size_slug: professional-xs
    run_command: uv run celery -A app.tasks worker --loglevel=info --concurrency=2
