"""add extended model fields

Revision ID: ac190f372658
Revises: e959d26d2af2
Create Date: 2026-02-21 23:26:45.989541

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac190f372658'
down_revision: str | Sequence[str] | None = 'e959d26d2af2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apiaries', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('apiaries', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('apiaries', sa.Column('hex_color', sa.String(length=7), nullable=True))
    op.add_column('hives', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('hives', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('impression', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('attention', sa.Boolean(), nullable=True))
    op.add_column('inspections', sa.Column('reminder', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('queens', sa.Column('race', sa.String(length=100), nullable=True))
    op.add_column('queens', sa.Column('quality', sa.Integer(), nullable=True))
    op.add_column('queens', sa.Column('fertilized', sa.Boolean(), nullable=False))
    op.add_column('queens', sa.Column('clipped', sa.Boolean(), nullable=False))
    op.add_column('queens', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    op.drop_column('users', 'name')
    op.drop_column('queens', 'birth_date')
    op.drop_column('queens', 'clipped')
    op.drop_column('queens', 'fertilized')
    op.drop_column('queens', 'quality')
    op.drop_column('queens', 'race')
    op.drop_column('inspections', 'reminder_date')
    op.drop_column('inspections', 'reminder')
    op.drop_column('inspections', 'attention')
    op.drop_column('inspections', 'impression')
    op.drop_column('hives', 'order')
    op.drop_column('hives', 'color')
    op.drop_column('apiaries', 'hex_color')
    op.drop_column('apiaries', 'country_code')
    op.drop_column('apiaries', 'city')
    # ### end Alembic commands ###
