import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const SCHEMA_VERSION = 1;

export default appSchema({
  version: SCHEMA_VERSION,
  tables: [
    tableSchema({
      name: "apiaries",
      columns: [
        { name: "name", type: "string" },
        { name: "latitude", type: "number", isOptional: true },
        { name: "longitude", type: "number", isOptional: true },
        { name: "city", type: "string", isOptional: true },
        { name: "country_code", type: "string", isOptional: true },
        { name: "hex_color", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "archived_at", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "hives",
      columns: [
        { name: "apiary_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "hive_type", type: "string" },
        { name: "status", type: "string" },
        { name: "source", type: "string", isOptional: true },
        { name: "installation_date", type: "string", isOptional: true },
        { name: "color", type: "string", isOptional: true },
        { name: "position_order", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "queens",
      columns: [
        { name: "hive_id", type: "string", isIndexed: true },
        { name: "marking_color", type: "string", isOptional: true },
        { name: "marking_year", type: "number", isOptional: true },
        { name: "origin", type: "string", isOptional: true },
        { name: "status", type: "string" },
        { name: "race", type: "string", isOptional: true },
        { name: "quality", type: "number", isOptional: true },
        { name: "fertilized", type: "boolean" },
        { name: "clipped", type: "boolean" },
        { name: "birth_date", type: "string", isOptional: true },
        { name: "introduced_date", type: "string", isOptional: true },
        { name: "replaced_date", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "inspections",
      columns: [
        { name: "hive_id", type: "string", isIndexed: true },
        { name: "inspected_at", type: "number" },
        { name: "duration_minutes", type: "number", isOptional: true },
        { name: "experience_template", type: "string" },
        { name: "observations_json", type: "string", isOptional: true },
        { name: "weather_json", type: "string", isOptional: true },
        { name: "impression", type: "number", isOptional: true },
        { name: "attention", type: "boolean", isOptional: true },
        { name: "reminder", type: "string", isOptional: true },
        { name: "reminder_date", type: "number", isOptional: true },
        { name: "ai_summary", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "inspection_photos",
      columns: [
        { name: "inspection_id", type: "string", isIndexed: true },
        { name: "s3_key", type: "string" },
        { name: "caption", type: "string", isOptional: true },
        { name: "ai_analysis_json", type: "string", isOptional: true },
        { name: "url", type: "string", isOptional: true },
        { name: "uploaded_at", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "treatments",
      columns: [
        { name: "hive_id", type: "string", isIndexed: true },
        { name: "treatment_type", type: "string" },
        { name: "product_name", type: "string", isOptional: true },
        { name: "method", type: "string", isOptional: true },
        { name: "started_at", type: "number", isOptional: true },
        { name: "ended_at", type: "number", isOptional: true },
        { name: "dosage", type: "string", isOptional: true },
        { name: "effectiveness_notes", type: "string", isOptional: true },
        { name: "follow_up_date", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "harvests",
      columns: [
        { name: "hive_id", type: "string", isIndexed: true },
        { name: "harvested_at", type: "number", isOptional: true },
        { name: "weight_kg", type: "number", isOptional: true },
        { name: "moisture_percent", type: "number", isOptional: true },
        { name: "honey_type", type: "string", isOptional: true },
        { name: "flavor_notes", type: "string", isOptional: true },
        { name: "color", type: "string", isOptional: true },
        { name: "frames_harvested", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "events",
      columns: [
        { name: "hive_id", type: "string", isIndexed: true },
        { name: "event_type", type: "string" },
        { name: "occurred_at", type: "number" },
        { name: "details_json", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "tasks",
      columns: [
        { name: "hive_id", type: "string", isOptional: true },
        { name: "apiary_id", type: "string", isOptional: true },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "due_date", type: "string", isOptional: true },
        { name: "recurring", type: "boolean" },
        { name: "recurrence_rule", type: "string", isOptional: true },
        { name: "source", type: "string" },
        { name: "completed_at", type: "number", isOptional: true },
        { name: "priority", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "task_cadences",
      columns: [
        { name: "hive_id", type: "string", isOptional: true },
        { name: "cadence_key", type: "string" },
        { name: "is_active", type: "boolean" },
        { name: "last_generated_at", type: "number", isOptional: true },
        { name: "next_due_date", type: "string", isOptional: true },
        { name: "custom_interval_days", type: "number", isOptional: true },
        { name: "custom_season_month", type: "number", isOptional: true },
        { name: "custom_season_day", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
  ],
});
